### ISSUE TITLE
move from nlmrt to nlsr?

### ISSUE THREAD

**Issue by bbolker** [brentkaplan/beezdemand#13]
I was just having a conversation with John Nash, the maintainer of the `nlmrt` package, who says that package is out of date and should be replaced by `nlsr`. Without looking at the code I can't say how hard it will be to migrate, but if you did so it would allow him to archive/deprecate the package on CRAN (your package is the only reverse dependency of `nlmrt` on CRAN).

**Comment by brentkaplan** [comment]
Can do. Will see if I can get it done soon.

**Comment by bbolker** [comment]
thanks!
