### ISSUE TITLE
Resulting data frame

### ISSUE THREAD

**Issue by miyamot0** [brentkaplan/beezdemand#5]
Per the latest version, I can't assign the results to a variable (e.g., "xyz = FitCurve(...)"). It seems to operate as a pointer to the function, calling the function every time that attempt to print the output.

Is this expected functionality? Is there some type of reference that can be passed in to call results directly?

**Comment by brentkaplan** [comment]
Hmm. It should return the data frame of results as before. Could you try changing the argument 'detailed = FALSE' to 'detailed = TRUE' and see if the return object is a list?
